server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /fish-tracker

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fish-tracker-pg
    driver-class-name: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework: INFO
    com.jerzyboksa: DEBUG

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: ${JWT_EXPIRATION_TIME}

custom:
  image_path: ${IMAGE_PATH}